# Workflow is based on the Astropy GitHub actions workflow, ci_workflows.yml
name: CI

on:
    push:
        branches:
            - '*'
        tags:
            - '*'
    pull_request:

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                include:
                    - name: Code style checks
                      os: ubuntu-latest
                      python: 3.x
                      toxenv: codestyle

                    - name: Test building of Sphinx docs
                      os: ubuntu-latest
                      python: 3.9
                      toxenv: build_docs

                    - name: Python 3.9 withcoverage checking
                      os: ubuntu-latest
                      python: 3.9
                      toxenv: py38-test-cov

                    - name: Python 3.7
                      os: ubuntu-latest
                      python: 3.7
                      toxenv: py37-test

                    - name: Python 3.8
                      os: ubuntu-latest
                      python: 3.8
                      toxenv: py38-test

                    - name: Python 3.9
                      os: ubuntu-latest
                      python: 3.9
                      toxenv: py39-test

                    - name: Python 3.10
                      os: ubuntu-latest
                      python: 3.10
                      toxenv: py310-test

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Set up Python ${{ matrix.python }} on ${{ matrix.os }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}
            - name: Install Python dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install tox
            - name: Run the test with tox
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: tox -e ${{ matrix.toxenv }}
